In [11]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[20, 6]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[7, 13], [20, 6], [8, 4], [2, 15, 27], [6, 8, 12], [28, 13], [22, 8, 7], [27, 21], [27, 20], [17, 17]]


In [4]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 7 13  0]
 [20  6  0]
 [ 8  4  0]
 [ 2 15 27]
 [ 6  8 12]
 [28 13  0]
 [22  8  7]
 [27 21  0]
 [27 20  0]
 [17 17  0]]


In [15]:
embeded_vector_size = 5

model = Sequential()
model.add(Input(shape=(max_length,)))
model.add(Embedding(vocab_size, embeded_vector_size,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [16]:
X = padded_reviews
y = sentiment

In [17]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 3, 5)                │             150 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_2 (Flatten)                  │ (None, 15)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              16 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 166 (664.00 B)

 Trainable params: 166 (664.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [18]:
model.fit(X, y, epochs=50, verbose=0)

In [19]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - accuracy: 1.0000 - loss: 0.6075


1.0

In [20]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [21]:
weights[13]

array([-0.04414885,  0.04486331, -0.03439729,  0.00986067,  0.04070358],
      dtype=float32)

In [22]:
weights[4]

array([ 6.3482754e-02,  1.9022232e-02,  6.4596780e-02, -4.3812906e-06,
        5.7643853e-02], dtype=float32)

In [23]:
weights[16]

array([ 0.03807993,  0.02910768,  0.01318767, -0.00343562, -0.02509521],
      dtype=float32)